version: '3.7'
services:
  db:
    container_name: nodejs-service-postgres
    image: nodejs-service-postgres
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - nodejs-service-net
  nodejs-service:
    container_name: nodejs-service
    image: nodejs-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    networks:
      - nodejs-service-net

volumes:
  pgdata:

networks:
  nodejs-service-net:
    name: nodejs-service-net
    driver: bridge
