version: '3.7'
services:
  db:
    container_name: nodejs-service-postgres
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  nodejs-service:
    image: nodejs-service
    build: .
    ports:
      - '4000:4000'
